config/routes.rb
FlashCards::Application.routes.draw do
  resources :terms

  resources :categories

  get "/exams/:id/terms/new" => "terms#new"
  resources :exams

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :exams
  validates_uniqueness_of :name
  validates_presence_of :name
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  attr_accessible :name, :description, :category_id, :term_ids
  belongs_to :category
  has_and_belongs_to_many :terms
  validates_uniqueness_of :name
  validates_presence_of :name
end

app/models/term.rb
class Term < ActiveRecord::Base
  attr_accessible :word, :definition, :exam_ids
  has_and_belongs_to_many :exams
  validates_uniqueness_of :word
  validates_presence_of :word
  validates_presence_of :definition
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
	format.html { redirect_to @category, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
	format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, :notice => 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
    @exams = Exam.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @exams }
    end
  end

  def show
    @exam = Exam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @exam }
    end
  end

  def new
    @exam = Exam.new
    @categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @exam }
    end
  end

  def edit
    @exam = Exam.find(params[:id])
    @categories = Category.all
  end

  def create
    @exam = Exam.new(params[:exam])

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, :notice => 'Exam was successfully created.' }
        format.json { render :json => @exam, :status => :created, :location => @exam }
      else
        format.html { render :action => "new" }
        format.json { render :json => @exam.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @exam = Exam.find(params[:id])

    respond_to do |format|
      if @exam.update_attributes(params[:exam])
        format.html { redirect_to @exam, :notice => 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @exam.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy

    respond_to do |format|
      format.html { redirect_to exams_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @terms }
    end
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
    @term = Term.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @term }
    end
  end

  # GET /terms/new
  # GET /terms/new.json
  def new
    @term = Term.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @term }
    end
  end

  # GET /terms/1/edit
  def edit
    @term = Term.find(params[:id])
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(params[:term])

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, :notice => 'Term was successfully created.' }
        format.json { render :json => @term, :status => :created, :location => @term }
      else
        format.html { render :action => "new" }
        format.json { render :json => @term.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /terms/1
  # PUT /terms/1.json
  def update
    @term = Term.find(params[:id])

    respond_to do |format|
      if @term.update_attributes(params[:term])
        format.html { redirect_to @term, :notice => 'Term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @term.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term = Term.find(params[:id])
    @term.destroy

    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="form">
<h1>Editing category</h1>

<%= form_for(@category, :html => { :multipart => true }) do |f| %>
  <p>Category Name:<br>
  <%= f.text_field :name %></p>
  <% f.submit "Submit" %>
   <%= f.submit "Update Category", :class => "btn" %>
<% end %><br><br>

<%= link_to 'Show Category', @category %> |
<%= link_to 'All Categories', categories_path %>
</div>

app/views/categories/index.html.erb
<a href="/exams">View Exams</a>&nbsp;&nbsp;|&nbsp;
<a href="/terms">View Terms</a>

<div class="display">
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Category Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name  %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br><br>

<%= link_to 'Add New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<div class="form">
  <h1>New category</h1>

  <%= form_for(@category, :html => { :multipart => true }) do |f| %>
    <p>Category Name:<br>   
    <%= f.text_field :name %></p>
    <% f.submit "Submit" %>
    <%= f.submit "Add Category", :class => "btn" %>
  <% end %>
  <br><br>
  <%= link_to 'All Categories', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="form">
<p id="notice"><%= notice %></p>

<h1><%=  @category.name %></h1>
<h4>Exams</h4>

<% @category.exams.all.each do |e| %>
<%= e.name %><br>
<%end%><br><br>


<%= link_to 'Edit Category', edit_category_path(@category) %> |
<%= link_to 'All Categories', categories_path %>
</div>

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<div class="form">
<h1>Editing exam</h1>

<%= form_for(@exam, :html => { :multipart => true }) do |f| %>
  <p>Exam Name:<br>
  <%= f.text_field :name %></p>

  <p>Description:<br>
  <%= f.text_area :description %></p>

  <p> <%= f.collection_select(:category_id, Category.all, :id, :name)%></p>
  <%= f.submit "Update Exam", :class => "btn" %>
<% end %><br><br>

<%= link_to 'Show Exam', @exam %> |
<%= link_to 'All Exams', exams_path %>
</div>

app/views/exams/index.html.erb
<a href="/categories">View Categories</a>&nbsp;&nbsp;|&nbsp;
<a href="/terms">View Terms</a>

<div class="display">
<h1>Listing exams</h1>

<table>
  <tr>
    <th>Exam</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @exams.each do |exam| %>
  <tr>
    <td><%= exam.name %></td>
    <td><%= exam.category.name %></td>
    <td><%= link_to 'Show', exam %></td>
    <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
    <td><%= link_to 'Destroy', exam, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br><br>

<%= link_to 'Add New Exam', new_exam_path %>
</div>

app/views/exams/new.html.erb
<div class="form">
<h1>New exam</h1>

<%= form_for(@exam, :html => { :multipart => true }) do |f| %>
  <p>Exam Name:<br>
  <%= f.text_field :name %></p>
  
  <p>Description:<br>
  <%= f.text_area :description %></p>
 
  <p> <%= f.collection_select(:category_id, Category.all, :id, :name)%></p>
  <%= f.submit "Add Exam", :class => "btn" %>
<% end %><br><br>


<%= link_to 'All Exams', exams_path %>
</div>

app/views/exams/show.html.erb
<div class="form">
<p id="notice"><%= notice %></p>
<h1><%= @exam.name %></h1>
<h4 class="subtitle"><%= @exam.category.name %></h4>

<h4>Terms:</h4>
<% @exam.terms.all.each do |t| %>
<%= t.word %><br>
<%end%><br><br>

<%= link_to 'Edit Exam', edit_exam_path(@exam) %> |
<%= link_to 'All Exams', exams_path %> | 
<%= link_to 'Add Existing Term', terms_path %> | 
<%= link_to 'Add New Term', new_term_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlashCards</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/terms/_form.html.erb
<%= form_for(@term) do |f| %>
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% @term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terms/edit.html.erb
<div class="form">
<h1>Editing term</h1>

<%= form_for(@term, :html => { :multipart => true }) do |f| %>
  <p>Word:<br>
  <%= f.text_field :word %></p>

  <p>Definition:<br>
  <%= f.text_area :definition %></p>

  <% for exam in Exam.all %>
    <%= check_box_tag "term[exam_ids][]", exam.id, @term.exams.include?(exam) %>
    <%= exam.name %>
  <% end %><br><br>

  <%= f.submit "Update Term", :class => "btn" %>
<% end %><br><br>


<%= link_to 'Show Term', @term %> |
<%= link_to 'All Terms', terms_path %>
</div>

app/views/terms/index.html.erb
<a href="/categories">View Categories</a>&nbsp;&nbsp;|&nbsp;
<a href="/exams">View Exams</a>

<div class="display">
<h1>Listing terms</h1>

<table>
  <tr>
    <th>Word</th>
    <th>Definition</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @terms.each do |term| %>
  <tr>
    <td><%= term.word %></td>
    <td><%= term.definition %></td>
    <td><%= link_to 'Show', term %></td>
    <td><%= link_to 'Edit', edit_term_path(term) %></td>
    <td><%= link_to 'Destroy', term, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br><br>

<%= link_to 'Add New Term', new_term_path %>
</div>

app/views/terms/new.html.erb
<div class="form">
<h1>New term</h1>

<%= form_for(@term, :html => { :multipart => true }) do |f| %>
  <p>Word:<br>
  <%= f.text_field :word %></p>

  <p>Definition:<br>
  <%= f.text_area :definition %></p>

  <% for exam in Exam.all %>  
    <%= check_box_tag "term[exam_ids][]", exam.id, @term.exams.include?(exam) %>  
    <%= exam.name %>  
  <% end %><br><br>

  <%= f.submit "Add Term", :class => "btn" %>
<% end %>
<br><br>
<%= link_to 'All Terms', terms_path %>
</div>

app/views/terms/show.html.erb
<div class="form">
<p id="notice"><%= notice %></p>

<h1><%=  @term.word %></h1>
<h3><%= @term.definition %></h3>
<h4>Exams</h4>

<% @term.exams.all.each do |e| %>
<%= e.name %><br>
<%end%><br><br>

<%= link_to 'Edit Term', edit_term_path(@term) %> |
<%= link_to 'All Terms', terms_path %>
</div>